image: docker:19.03.12
variables:
  DOCKER_TLS_CERTDIR: "/certs"
services:
- docker:19.03.12-dind
default:
  before_script:
  - docker info

stages:
  - build


build_image:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    # https://docs.gitlab.com/ee/user/packages/container_registry/#authenticate-by-using-gitlab-cicd
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG