name: Publish PHP 7.2 image to Docker Hub
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker Build & Push Action
        # You may pin to the exact commit or the version.
        # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          # Name of the Docker image
          image: default/nginx-php-fpm-72
          # Tags override for Docker image
          tags: $GITHUB_REF_NAME
          # Target Docker registry
          registry: ${{ secrets.DOCKER_REGISTRY }}
          # Docker registry username
          username: ${{ secrets.DOCKER_USERNAME }}
          # Docker registry password
          password: ${{ secrets.DOCKER_PASSWORD }}
